// Does not require a live GemStone/S stone.
//
// Expected output starts with:
//
// output: src/generated/gemstone_wrappers.rs
// // @generated by gemstone-rs codegen. Do not edit by hand.

use gemstone_rs::codegen;

fn main() -> codegen::Result<()> {
    let config = codegen::Config::parse(codegen::sample_config(), None)?;
    let generated = codegen::generate(&config);

    println!("output: {}", generated.output.display());
    println!("{}", generated.source);
    Ok(())
}
