// @generated by gemstone-rs codegen. Do not edit by hand.
use gemstone_rs::{Error, Oop, Result, Session, Value};

pub struct Object<'a> {
    session: &'a mut Session,
    oop: Oop,
}

impl<'a> Object<'a> {
    pub fn from_oop(session: &'a mut Session, oop: Oop) -> Self {
        Self { session, oop }
    }

    pub fn print_string(&mut self) -> Result<String> {
        let value = self.session.perform(self.oop, "printString", &[])?;
        match value {
            Value::String(value) => Ok(value),
            Value::Oop(oop) => self.session.fetch_string(oop),
            other => Err(Error::UnexpectedType {
                expected: "String",
                actual: format!("{other:?}"),
            }),
        }
    }
}
